### ISSUE TITLE
[Close loop dynamics] Vehicle + Trailer dynamics 

### ISSUE THREAD

**Issue by jcontrolresearch** [lfc-256/ControlBDA#21]
Design and implement a model on Simulink based on dynamics model explained in this [issue](https://github.com/lfc-256/ControlBDA/issues/20).

Tested in following conditions:

- Reverse movement
- Straight line maneuver (or step response)
- Please follow @raul-rd  [implementation ](https://github.com/lfc-256/ControlBDA/issues/15)to show trailer and vehicle direction.

**Comment by jcontrolresearch** [comment]
@raul-rd  investigate how to calculate center of mass. This is a good reference? [link](https://www.cjponyparts.com/resources/center-of-gravity-infographic)

**Comment by raul-rd** [comment]
This it's a good reference [link](https://www.cjponyparts.com/resources/center-of-gravity-infographic) to calculate center of mass of a vehicle. Moreover I found a [Car Center of Mass Calculator](https://www.omnicalculator.com/physics/car-mass-center#how-to-find-the-center-of-gravity-of-a-car).

Four parameters are necessary to calculate the longitudinal position: vehicle weight, front and rear axle weight and the wheelbase.
For the calculation, I consider the permissible  axles  weights  provided by the manufacturer [here](https://www.volvocars.com/en-ca/support/manuals/xc90/2019-late/specifications/dimensions-and-weights/weights).

According to the notacion in the [paper](https://github.com/lfc-256/ControlBDA/blob/12d2a0e93dcda8489a7854225dc57a16fe4c50fd/External/Bibliography/Stability%20and%20Control_vechicle-trailer%20combination.pdf), the center of mass of the Volvo XC90 Late is located at:
- a1=62.51 in
- b1=54.99 in

@JControlReserch @lfc-256 @SaraML @HugoLeyvaOax
