### ISSUE TITLE
Merge vehicle + trailer presentation document

### ISSUE THREAD

**Issue by jcontrolresearch** [lfc-256/ControlBDA#27]
Please just merge presentation document to close :) thanks for the effort

_Originally posted by @JControlReserch in https://github.com/lfc-256/ControlBDA/issues/20#issuecomment-637768830_

**Comment by jcontrolresearch** [comment]
@SaraML  I can't find any change or addition from previous verison on PP presentation, please check this :)

**Comment by SaraML** [comment]
I made a new commit 639cf86b7dd1de9a976f5264903bf155e19bd8f2. I don't know why it doesn't show changes, but the presentation seems to be completed

**Comment by jcontrolresearch** [comment]
> I made a new commit [639cf86](https://github.com/lfc-256/ControlBDA/commit/639cf86b7dd1de9a976f5264903bf155e19bd8f2). I don't know why it doesn't show changes, but the presentation seems to be completed

I get it now. I'll close this issue.
Thanks
