### ISSUE TITLE
Scrum + Kanban Ramp up

### ISSUE THREAD

**Issue by jcontrolresearch** [lfc-256/ControlBDA#4]
How to share knowledge on  Scrum + Kanban?
How to ramp up team on?
Build some presentation to ramp up?
Schedule a ramp up meeting to 1/05/2020

Useful links:
[Scrum overview](https://www.youtube.com/watch?v=XU0llRltyFM)
[Kanban overview](https://www.youtube.com/watch?v=R8dYLbJiTUE)

**Comment by jcontrolresearch** [comment]
Scrum rules resource:

- Scrum Guide Highligthed

[here](http://pashunconsulting.co.uk/pdf/2017-Scrum-Guide-US-highlighted_.pdf)

**Comment by SaraML** [comment]
We already watched the videos but we have problems using Virto Kanban on Teams. We couldn't schedule the meeting.

**Comment by jcontrolresearch** [comment]
@SaraML , please refer to [here](https://github.com/lfc-256/ControlBDA/projects/2) for project kanban board.
I tried to use Virtus on Teams but isn't efficient for this project. Just avoid it.

Backlog and roles will be defined on Monday 04/05 on first stand up meeting.
