### ISSUE TITLE
[Documentation] Look for car parameters

### ISSUE THREAD

**Issue by jcontrolresearch** [lfc-256/ControlBDA#7]
From Ackermann model, look parameter to match with real vehicle

**Comment by SaraML** [comment]
[CAR PARAMETERS.pdf](https://github.com/lfc-256/ControlBDA/files/4589816/CAR.PARAMETERS.pdf)

We selected the Volvo XC90 2019 because we have the necessary parameters

**Comment by jcontrolresearch** [comment]
> [CAR PARAMETERS.pdf](https://github.com/lfc-256/ControlBDA/files/4589816/CAR.PARAMETERS.pdf)
> 
> We selected the Volvo XC90 2019 because we have the necessary parameters

@SaraML, please update file on external/
