### ISSUE TITLE
[Model design] Bicycle model vehicle

### ISSUE THREAD

**Issue by jcontrolresearch** [lfc-256/ControlBDA#8]
Create a model black box to bicycle.

Please define following sections before design model
(Document on wiki)
Inputs:
Output:
Parameters:

**Comment by SaraML** [comment]
Bicycle model
Inputs:

- v=Speed

- Df=Angle between the front Wheel and the car

Outputs:

- psi1=Orientation of frame L1

- gam1=deference between orientation of frame L1 and frame L2 

- x1,y1=position of frame L1

L1 is the car's frame

**Comment by jcontrolresearch** [comment]
@lfc-256 , @SaraML , @raul-rd , will generate simulink model and step response due to Friday May, 15 (at least some progress).
Reference to [Book](https://github.com/lfc-256/ControlBDA/blob/master/External/Bibliography/FULLTEXT01.pdf), page 15.
