### ISSUE TITLE
[Model design] Generate a variable dictionary and values

### ISSUE THREAD

**Issue by jcontrolresearch** [lfc-256/ControlBDA#9]
Create a dictionary including all parameters or variables.
(In simulink it must be add variables to  Workspace)

**Comment by lfc-256** [comment]
The dictionary was include in the folder Scripts, with the following names:

- variable_dictionary.m

- variable_dictionary.sce

**Comment by jcontrolresearch** [comment]
@raul-rd please update dictionary to include trailer parameters, please complete ASAP in order to not be a blocker to [issue](https://github.com/lfc-256/ControlBDA/issues/21). #21
